import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const dirs = [
	"/Users/xy/Library/Mobile Documents/iCloud~md~obsidian/Documents/obsidian-demo/.obsidian/plugins/obsidian-snippets-manager",
	"/Users/xy/Library/Mobile Documents/iCloud~md~obsidian/Documents/bfcs/.obsidian/plugins/obsidian-snippets-manager",
];

const copyFiles = () => {
	for (const dir of dirs) {
		if (!fs.existsSync(dir)) {
			fs.mkdirSync(dir, { recursive: true });
		}
		if (fs.existsSync("main.js")) {
			fs.copyFileSync("main.js", path.join(dir, "main.js"));
		}
		if (fs.existsSync("manifest.json")) {
			fs.copyFileSync("manifest.json", path.join(dir, "manifest.json"));
		}
		if (fs.existsSync("styles.css")) {
			fs.copyFileSync("styles.css", path.join(dir, "styles.css"));
		}
	}
	console.log("Manifest, Styles, and JS synced to vaults.");
};

const copyPlugin = {
	name: "copy-files",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length === 0) {
				copyFiles();
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/plugin/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
