import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const dir = "/Users/xy/Repo/obsidian-vault-bfcs/.obsidian/plugins/obsidian-snippets-manager";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/plugin/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${dir}/main.js`,
	minify: prod,
});

const copyFiles = () => {
	if (!fs.existsSync(dir)) {
		fs.mkdirSync(dir, { recursive: true });
	}
	fs.copyFileSync("manifest.json", path.join(dir, "manifest.json"));
	if (fs.existsSync("styles.css")) {
		fs.copyFileSync("styles.css", path.join(dir, "styles.css"));
	}
	console.log("Manifest and Styles synced to vault.");
};

if (prod) {
	await context.rebuild();
	copyFiles();
	process.exit(0);
} else {
	await context.watch();
	copyFiles();
}
